# orchestrator.yml — blueprint entrypoint
- name: Load data and orchestrate roles
  hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ lookup('env','UNYCA_BUILD_DIR') }}/data.json"

  tasks:
    - name: Prepare SSH key file if inline (temp 0600)
      when: item.inline_ssh_key_b64 is defined
      ansible.builtin.copy:
        dest: "/tmp/unyca_{{ item.id }}.key"
        content: "{{ item.inline_ssh_key_b64 | b64decode }}"
        mode: "0600"
      loop: "{{ data }}"
      loop_control: { label: "{{ item.id }}" }

    - name: Add hosts dynamically
      ansible.builtin.add_host:
        name: "{{ item.id }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: "{{ item.user }}"
        ansible_connection: "{{ item.connection | default('ssh') }}"
        ansible_private_key_file: >-
          {{ (item.ssh_key | default()) | ternary(item.ssh_key, '/tmp/unyca_' ~ item.id ~ '.key') }}
        groups: "{{ item.groups }}"
        vars: "{{ item.vars | default({}) }}"
      loop: "{{ data }}"
      loop_control: { label: "{{ item.id }}" }

- name: Apply database role
  hosts: databases
  gather_facts: false
  roles: [ servers/databases ]

- name: Apply API role
  hosts: apis
  gather_facts: false
  roles: [ servers/apis ]

- name: Apply game node role
  hosts: game-nodes
  gather_facts: false
  roles: [ servers/game-nodes ]
